\i src/db/scripts/sql/schemas.sql
\i src/db/scripts/sql/extensions.sql
\i src/db/scripts/sql/settings.sql
\i src/db/scripts/sql/sequences.sql
\i src/db/scripts/sql/functions.sql
\i src/db/scripts/sql/views.sql
\i src/db/scripts/sql/enums.sql
\i src/db/scripts/sql/tables.sql
\i src/db/scripts/sql/triggers.sql
\i src/db/scripts/sql/comments.sql
