version: '3'

services:
  # orders-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: normanfx/workflyt
  #   container_name: workflyt
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #   env_file: ./.env.dev

  postgres-database:
    image: postgres:10.10
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=workflyt
