const faker = require('faker');

module.exports = [
  {
    id: faker.random.uuid(),
    code: 'EMP/001',
    firstname: 'Luis',
    lastname: 'Berrios',
    is_supervisor: 0,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/002',
    firstname: 'Danilo',
    lastname: 'Briceño',
    is_supervisor: 0,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/003',
    firstname: 'Javier',
    lastname: 'Vasquez',
    is_supervisor: 1,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/004',
    firstname: 'Denis',
    lastname: 'Vasquez',
    is_supervisor: 1,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/005',
    firstname: 'Jorge',
    lastname: 'Bográn',
    is_supervisor: 0,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/006',
    firstname: 'Erick',
    lastname: 'Lopez',
    is_supervisor: 0,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  },
  {
    id: faker.random.uuid(),
    code: 'EMP/007',
    firstname: 'Luís',
    lastname: 'Lopez',
    is_supervisor: 0,
    extra: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    created_by: null,
    updated_by: null,
    deleted_by: null
  }
];
