-- DROP DATABASES:
DROP DATABASE IF EXISTS workflyt_test;
DROP DATABASE IF EXISTS workflyt_dev;
DROP DATABASE IF EXISTS workflyt_stage;
DROP DATABASE IF EXISTS workflyt;

-- CREATE DATABASES:
CREATE DATABASE workflyt_test WITH OWNER dev;
CREATE DATABASE workflyt_dev WITH OWNER dev;
CREATE DATABASE workflyt_stage WITH OWNER dev;
CREATE DATABASE workflyt WITH OWNER dev;

-- DROP FUNCTIONS:
DROP FUNCTION IF EXISTS gen_code(text[]);

-- CREATE FUNCTIONS:

-- \d
\l
